CREATE TABLE contact_type_lookup (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL /* e.g. Phone or email */
);

CREATE TABLE contact_sub_type_lookup (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL /* e.g. Home or Mobile or Work */
);

CREATE TABLE external_system_lookup (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL, /* e.g. CRM and UH */
    description varchar(255)
);

CREATE TABLE residents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(255),
    last_name varchar(255),
    date_of_birth timestamp,
    gender char(1)
);

CREATE TABLE contact_details (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_type_lookup_id integer REFERENCES contact_type_lookup (id) NOT NULL,
    contact_subtype_lookup_id integer REFERENCES contact_sub_type_lookup (id),
    contact_details_value varchar(255),
    is_default boolean NOT NULL,
    is_active boolean NOT NULL,
    added_by varchar(255),
    date_added timestamp NOT NULL,
    date_modified timestamp NOT NULL,
    modified_by varchar(255),
    resident_id integer REFERENCES residents (id)
);

CREATE TABLE external_system_ids (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resident_id integer REFERENCES residents (id),
    external_id_value varchar(255) NOT NULL,
    external_id_name varchar(255) NOT NULL, /* e.g. Contact Id or Person Ref or House Ref */
    external_system_lookup_id integer REFERENCES external_system_lookup (id)
);

